### PR TITLE
Provide a specific Camel/Fuse command #21

### PR DESCRIPTION
**Pull request by apupier**
What do you think of this approach?

there are 2 commands:
image

the Camel/Fuse is filtering the missions which are providing Camel/Fuse runtime boosters:
image

the "generic" one is still available and working as before:
image

### CODE REVIEW

**Comment by jeffmaury** [comment]
I'm a little bit reluctant about having some FUSE specific code in this generic extension. What about calling the command from a FUSE specific extension and allowing the filter to be passed ?

**Comment by apupier** [comment]
> What about calling the command from a FUSE specific extension and allowing the filter to be passed ?

I'm still new with VS Code development. I thought that we can't have dependencies to other VS Code extensions easily. That they need to be published as npm module. I know that for vscode java it is not the case for instance.
Is it possible to have dependencies on VS Code extensions in another way than publishing to npm? Or maybe it is easy to publish this extension on npm?

**Comment by jeffmaury** [comment]
No but you can have a light dependency: search the command by its id and if found execute the command with parameter otherwise ask the user to install the Project Initializer extension.

**Comment by apupier** [comment]
> No but you can have a light dependency: search the command by its id and if found execute the command with parameter otherwise ask the user to install the Project Initializer extension.

:'(
Given that it makes things complicated in the other extensions to maintain i think it would be best to keep it in this extension.
if we want to add the same for vert.x or springboot runtime for instance, it means that we will have to create other extensions with a "light dependency". The day there is a refactor, we will have to change all of them and as there is a "light depdency" it will be hard to fidn them.
I think having another command for each specific runtime that we are aware of would be a great addition to this extension. It is giving another entry points to the boosters

**Comment by apupier** [comment]
@jeffmaury time to review it this week?

**Comment by apupier** [comment]
I really think that it is an important use case to cover.
I created a video to explain the difference between current state and what this PR is providing: https://drive.google.com/open?id=1rhzv9jP8cTpxTn7gqCtWxthfzYxvnMB5

**Comment by jeffmaury** [comment]
What about replacing these runtime specific commands (and issues we will have when one of those is removed from catalog) by a new runtime first command in addition to the existing mission first command.

**Comment by apupier** [comment]
> What about replacing these runtime specific commands (and issues we will have when one of those is removed from catalog)

I don't think that removal of a runtime will occur often.
it can be handled by checking availability of the runtime before registration of the command in the extension activation.

> by a new runtime first command in addition to the existing mission first command.

it is another possibility but it doesn't allow to find project creation command by typing the runtime name directly in the palette. Unless we put all available runtimes in the command name but it will give a very long command name. ( maybe not a big problem?)

**Comment by apupier** [comment]
> > What about replacing these runtime specific commands (and issues we will have when one of those is removed from catalog)
> it can be handled by checking availability of the runtime before registration of the command in the extension activation.

seems cannot be handled this way as the command is registered in the package.json, the "activate method is called only on first usage of the command

**Comment by apupier** [comment]
is it possible to reconsider this PR please?
it is improving drastically the User Experience for a minor additional maintenance effort (which will be higher if done in separated plugins).

**Pull request merged**
